- name: Install neovim plugins
  shell: |
    nvim --headless --cmd 'let g:df_setup = 1' '+Lazy! sync' '+Lazy load nvim-treesitter' '+Lazy! load mason-tool-installer.nvim' '+MasonToolsInstallSync' +qa
