- name: Install rust
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ ansible_facts['env'].HOME }}/.cargo/bin/rustup"

- name: Remove rustup shell modifications in shell configs
  lineinfile:
    path: "{{ item.path }}"
    line: '. "$HOME/.cargo/env"'
    state: absent
  when: item.exists
  loop: "{{ shell_configs }}"

- name: Remove rustup shell modifications in .profile
  lineinfile:
    path: "{{ dotprofile.path }}"
    line: '. "$HOME/.cargo/env"'
    state: absent
  when: zsh_config.exists

- name: Add cargo env to .zprofile
  lineinfile:
    path: "{{ zprofile.path }}"
    line: |
      [ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
    create: true
  when: zsh_config.exists
