- name: Install rust
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"

- name: Add cargo env to shell config
  blockinfile:
    path: "{{ item.path }}"
    block: |
      if [ -f "$HOME/.cargo/env" ]; then
          source "$HOME/.cargo/env"
      fi
    append_newline: true
    prepend_newline: true
    marker: "# {mark} dotfile:rust"
    marker_begin: '>>>'
    marker_end: '<<<'
  when: item.exists
  loop: "{{ shell_configs }}"

- name: Remove rustup shell modifications
  lineinfile:
    path: "{{ item.path }}"
    line: '. "$HOME/.cargo/env"'
    state: absent
  when: item.exists
  loop: "{{ shell_configs }}"
