- name: "{{ task_prefix}}Add red team shell block"
  blockinfile:
    path: "{{ shell_item.path }}"
    block: |
      function attack {
          name="$(echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^[:alnum:]]/_/g')"
          target="$2"

          if [ -z "$name" ]; then
              echo "error: target name is required"
              return 1
          fi
          if tmux has-session -t "$name" 2>/dev/null; then
              tmux attach-session -t "$name"
              return 0
          fi

          if [ -z "$target" ]; then
              echo "error: target IP is required"
              return 1
          fi

          boxdir="$HOME/boxes/$name"
          mkdir -p "$boxdir" && \
              tmux new-session -d -c "$boxdir" -s "$name" -e TARGET="$target" -e TARGET_NAME="$name" -e BOXDIR="$boxdir" && \
              tmux splitw -t "$name" -v -c "$boxdir" && \
              tmux rename-window -t "$name:1" recon && \
              tmux neww -c "$boxdir" -t "$name:" && \
              tmux neww -c "$boxdir" -t "$name:" && \
              tmux neww -c "$boxdir" -t "$name:" "ping -i 10 $target" && \
              tmux setw -t "$name:4" monitor-activity off && \
              tmux rename-window -t "$name:4" ping && \
              tmux selectw -t "$name:1" && \
              tmux selectp -t "$name:1.1" && \
              tmux attach-session -t "$name"
      }
    append_newline: true
    prepend_newline: true
    marker: "# {mark} dotfile:redteam"
    marker_begin: '>>>'
    marker_end: '<<<'
  when: shell_item.exists
  loop: "{{ shell_configs }}"
  loop_control:
    loop_var: shell_item
