- name: "{{ task_prefix}}Add red team shell block"
  blockinfile:
    path: "{{ shell_item.path }}"
    block: |
      function attack {
          name="$(echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^[:alnum:]]/_/g')"
          target="$2"

          if [ -z "$name" ]; then
              echo "error: target name is required"
              return 1
          fi
          if tmux has-session -t "$name" 2>/dev/null; then
              tmux attach-session -t "$name"
              return 0
          fi

          if [ -z "$target" ]; then
              echo "error: target IP is required"
              return 1
          fi

          boxdir="$HOME/boxes/$name"
          mkdir -p "$boxdir" && \
              tmux new-session -d -c "$boxdir" -s "$name" -e TARGET="$target" -e TARGET_NAME="$name" -e BOXDIR="$boxdir" && \
              tmux splitw -t "$name" -v -c "$boxdir" && \
              tmux rename-window -t "$name:1" recon && \
              tmux neww -c "$boxdir" -t "$name:" && \
              tmux neww -c "$boxdir" -t "$name:" && \
              tmux neww -c "$boxdir" -t "$name:" "ping -i 10 $target" && \
              tmux setw -t "$name:4" monitor-activity off && \
              tmux rename-window -t "$name:4" ping && \
              tmux selectw -t "$name:1" && \
              tmux selectp -t "$name:1.1" && \
              tmux attach-session -t "$name"
      }

      function urlencode {
          echo -n "$1" | python3 -c 'import urllib.parse;import sys;print(urllib.parse.quote_plus(sys.stdin.read(),safe="'"$2"'"))'
      }

      function urldecode {
          echo -n "$1" | python3 -c 'import urllib.parse;import sys;print(urllib.parse.unquote_plus(sys.stdin.read()))'
      }

      alias listen='nc -lvnp'
      alias serve='python3 -m http.server'
    append_newline: true
    prepend_newline: true
    marker: "# {mark} dotfile:redteam"
    marker_begin: '>>>'
    marker_end: '<<<'
  when: shell_item.exists
  loop: "{{ shell_configs }}"
  loop_control:
    loop_var: shell_item

- name: "{{task_prefix}}kerbrute | Query latest version"
  uri:
    url: https://api.github.com/repos/ropnop/kerbrute/releases/latest
  register: kerbrute_info
  changed_when: false

- name: "{{ task_prefix }}kerbrute | Download and install"
  get_url:
    url: "https://github.com/ropnop/kerbrute/releases/download/{{ kerbrute_info.json.tag_name }}/kerbrute_linux_amd64"
    dest: "/usr/local/bin/kerbrute"
    mode: 0755
  become: true

- name: "{{task_prefix}}bloodhound-cli | Query latest version"
  uri:
    url: https://api.github.com/repos/SpecterOps/bloodhound-cli/releases/latest
  register: bhcli_info
  changed_when: false

- name: "{{ task_prefix }}bloodhound-cli | Download and install"
  unarchive:
    remote_src: true
    src: "https://github.com/SpecterOps/bloodhound-cli/releases/download/{{ bhcli_info.json.tag_name }}/bloodhound-cli-linux-{{ ansible_machine | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}.tar.gz"
    dest: "/usr/local/bin"
    creates: "/usr/bin/local/bloodhound-cli"
    mode: 0755
  become: true
