- name: System configuration
  hosts: all

  pre_tasks:
    - name: Import pre-tasks
      include_tasks:
        file: "{{ item }}"
        apply:
          tags:
            - always
      with_fileglob: "pre_tasks/*.yml"
      tags:
        - always

  roles:
    - role: system
      tags:
        - system
    - role: grub
      tags:
        - grub
    - role: fzf
      tags:
      - fzf
    - role: git
      tags:
        - git
        - dev
    - role: nvim
      tags:
        - nvim
        - utils
    - role: tmux
      tags:
        - tmux
        - utils
    - role: vim
      tags:
        - vim
        - utils
    - role: redteam
      tags:
        - redteam
    - role: wayland
      tags:
        - wayland
    - role: x11
      tags:
        - x11
    - role: ohmyposh
      tags:
        - ohmyposh
        - omp
        - rice
    - role: lsd
      tags:
        - lsd
        - rice
    - role: xfce
      tags:
        - xfce
    - role: zsh
      tags:
        - zsh

    # run when on a desktop
    - role: fonts
      tags:
        - fonts
        - rice
      when: has_desktop | bool
    - role: kitty
      tags:
        - kitty
      when: has_desktop | bool

    # we want zoxide to run last, it adds a block to end of shell configs
    - role: zoxide
      tags:
        - zoxide
        - rice

    # run only if specified in tags
    - role: 1password
      tags:
        - 1password
        - never
    - role: bash
      tags:
        - bash
        - never
    - role: qterm
      tags:
        - qterm
        - never
    - role: sublime
      tags:
        - sublime
        - never
    - role: ghostty
      tags:
        - ghostty
        - never
    - role: go
      tags:
        - go
        - dev
        - never
    - role: rust
      tags:
        - rust
        - dev
        - never
    - role: gpg
      tags:
        - gpg
        - never
