- name: System configuration
  hosts: all

  pre_tasks:
    - import_tasks: "{{ playbook_dir }}/shared/pre_tasks.yml"

  roles:
    - role: system
      tags:
        - system
    - role: grub
      tags:
        - grub
    - role: proxmox
      tags:
        - proxmox
    - role: bash
      tags:
        - bash
    - role: zsh
      tags:
        - zsh
    - role: vim
      tags:
        - vim
        - utils
