- name: System configuration
  hosts: all

  pre_tasks:
    - name: Import pre-tasks
      include_tasks:
        file: "{{ item }}"
        apply:
          tags:
            - always
      with_fileglob: "pre_tasks/*.yml"
      tags:
        - always

  roles:
    - role: system
      tags:
        - system
        - common
    - role: grub
      tags:
        - grub
        - common
    - role: proxmox
      tags:
        - proxmox
        - common
    - role: bash
      tags:
        - bash
        - common
    - role: zsh
      tags:
        - zsh
        - common
    - role: vim
      tags:
        - vim
        - common
        - utils
