- name: System configuration
  hosts: all

  pre_tasks:
    - name: Import pre-tasks
      include_tasks:
        file: "{{ item }}"
        apply:
          tags:
            - always
      with_fileglob: "pre_tasks/*.yml"
      tags:
        - always

  roles:
    - role: system
      tags:
        - system
        - common
    - role: bash
      tags:
        - bash
        - common
    - role: zsh
      tags:
        - zsh
        - common
    - role: go
      tags:
        - go
        - dev
        - never
    - role: rust
      tags:
        - rust
        - dev
        - never
    - role: vim
      tags:
        - vim
        - common
        - utils
    - role: aptly
      tags:
        - aptly
        - pkg
        - never
    - role: gbp
      tags:
        - gbp
        - pkg
        - never
