- name: System configuration
  hosts: all

  pre_tasks:
    - import_tasks: "{{ playbook_dir }}/shared/pre_tasks.yml"

  roles:
    - role: system
      tags:
        - system
    - role: grub
      tags:
        - grub
    - role: bash
      tags:
        - bash
    - role: zsh
      tags:
        - zsh
    - role: git
      tags:
        - git
        - utils
    - role: gpg
      tags:
        - gpg
        - utils
    - role: vim
      tags:
        - vim
        - utils

    # run only if specified in tags
    - role: go
      tags:
        - go
        - dev
        - never
    - role: rust
      tags:
        - rust
        - dev
        - never
    - role: aptly
      tags:
        - aptly
        - pkg
        - never
    - role: gbp
      tags:
        - gbp
        - pkg
        - never
