[Appearance]
color_scheme_path=/usr/share/qt6ct/colors/Kali-Dark.conf
custom_palette=true
icon_theme=Flat-Remix-Blue-Dark
standard_dialogs=gtk3
style=Fusion

[Fonts]
fixed="JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Inter Display,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
stylesheets=/usr/share/qt6ct/qss/fusion-simple-scrollbar.qss
