[Appearance]
color_scheme_path=/usr/share/qt5ct/colors/Kali-Dark.conf
custom_palette=true
icon_theme=Flat-Remix-Blue-Dark
standard_dialogs=gtk3
style=Fusion

[Fonts]
fixed="JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0"
general="Inter Display,11,-1,5,50,0,0,0,0,0"

[Interface]
stylesheets=/usr/share/qt5ct/qss/fusion-simple-scrollbar.qss
