- ansible.builtin.import_tasks: "{{ playbook_dir }}/shared/include_os.yml"

- name: "Install oh-my-posh"
  shell: |
    curl -fsSL https://ohmyposh.dev/install.sh | bash -s -- -d "$HOME/.local/bin"
  args:
    creates: "{{ ansible_facts['env'].HOME }}/.local/bin/oh-my-posh"
  when: ansible_facts['system'] == 'Linux'

- name: "Update prompt"
  blockinfile:
    path: "{{ zsh_config.path }}"
    block: |
      autoload -Uz add-zsh-hook
      __newline_precmd() {
          $funcstack[1]() {
              echo
          }
      }
      add-zsh-hook precmd __newline_precmd

      VIRTUAL_ENV_DISABLE_PROMPT=1

      eval "$(oh-my-posh init zsh --config 'https://raw.githubusercontent.com/bwpge/zcmder-omp/main/zcmder.omp.json')"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} dotfile:omp"
    marker_begin: '>>>'
    marker_end: '<<<'
  when: zsh_config.exists
