- name: "{{ task_prefix}}Update system"
  become: true
  apt:
    update_cache: true
    upgrade: safe

- name: "{{ task_prefix}}Install utilities"
  become: true
  apt:
    state: latest
    pkg:
      - bat
      - fzf
      - jq
      - python3-venv
      - ripgrep
      - tmux
      - tree
      - vim

- name: "{{ task_prefix}}Add fzf key bindings"
  blockinfile:
    path: "{{ shell_item.path }}"
    block: |
      if command -v fzf > /dev/null 2>&1; then
          source <(fzf --{{ shell_item.name }})
      fi
    append_newline: true
    prepend_newline: true
    marker: "# {mark} dotfile:fzf"
    marker_begin: '>>>'
    marker_end: '<<<'
  when: shell_item.exists
  loop: "{{ shell_configs }}"
  loop_control:
    loop_var: shell_item
