- name: "{{ task_prefix}}Install packages"
  become: true
  apt:
    state: "{{ system_packages_state }}"
    pkg: "{{ system_packages_kali }}"

- name: "{{ task_prefix}}Check for ssh key"
  stat:
    path: ~/.ssh/id_ed25519
  register: sshkey_check

- name: "{{ task_prefix}}Create ssh key"
  shell: |
    ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
  args:
    executable: /bin/sh
  when: not sshkey_check.stat.exists

- name: "{{ task_prefix}}Check for rockyou"
  stat:
    path: /usr/share/wordlists/rockyou.txt.gz
  register: rockyou

- name: "{{ task_prefix}}Decompress rockyou.txt"
  command: gunzip -k /usr/share/wordlists/rockyou.txt.gz
  args:
    creates: /usr/share/wordlists/rockyou.txt
  become: true
  when: rockyou.stat.exists
