- name: "{{ os_id }} | Install extra packages"
  become: true
  apt:
    state: latest
    pkg:
      - joplin
      - kali-wallpapers-all
      - obsidian
      - seclists

- name: "{{ os_id }} | Check for ssh key"
  stat:
    path: ~/.ssh/id_ed25519
  register: sshkey_check

- name: "{{ os_id }} | Create ssh key"
  shell: |
    ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
  args:
    executable: /bin/sh
  when: not sshkey_check.stat.exists

- name: "{{ os_id }} | Decompress rockyou.txt"
  command: gunzip -k /usr/share/wordlists/rockyou.txt.gz
  args:
    creates: /usr/share/wordlists/rockyou.txt
  become: true
