- name: "{{ task_prefix}}Check for desktop environment"
  shell: apt list --installed 'kali-desktop*'
  register: _desktop
  changed_when: false

- name: "{{ task_prefix}}Install build tools"
  become: true
  apt:
    state: latest
    pkg:
      - build-essential
      - cmake
      - gettext
      - git
      - ninja-build

- name: "{{ task_prefix}}Install extra packages"
  become: true
  apt:
    state: latest
    pkg:
      - autorecon
      - feroxbuster
      - kali-wallpapers-all
      - seclists

- name: "{{ task_prefix }}Install desktop packages"
  become: true
  apt:
    state: latest
    pkg:
      - xsel
      - flameshot
  when: _desktop.stdout != ""

- name: "{{ task_prefix}}Check for ssh key"
  stat:
    path: ~/.ssh/id_ed25519
  register: sshkey_check

- name: "{{ task_prefix}}Create ssh key"
  shell: |
    ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
  args:
    executable: /bin/sh
  when: not sshkey_check.stat.exists

- name: "{{ task_prefix}}Decompress rockyou.txt"
  command: gunzip -k /usr/share/wordlists/rockyou.txt.gz
  args:
    creates: /usr/share/wordlists/rockyou.txt
  become: true
