- name: "{{ task_prefix }}Update system"
  community.general.homebrew:
    update_homebrew: true
    upgrade: true

- name: "{{ task_prefix }}Install packages"
  community.general.homebrew:
    state: latest
    pkg: "{{ system_packages_macos }}"
