- name: "{{ task_prefix }}Update system"
  community.general.homebrew:
    update_homebrew: true
    upgrade: true

- name: "{{ task_prefix }}Install build tools"
  community.general.homebrew:
    state: latest
    name: cmake,gettext,git,ninja

- name: "{{ task_prefix }}Install utilities"
  community.general.homebrew:
    state: latest
    pkg: bat,fzf,jq,lsd,ripgrep,tmux,tree
