- name: "{{ task_prefix }}Read zsh config"
  shell: "cat {{ zsh_config.path }}"
  register: oldzsh
  changed_when: false

- name: "{{ task_prefix }}Fix zsh suggest highlight"
  shell: >
    sed -i 's/^\([[:space:]]\+\)\(ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE\)/\1# \2/g'
    {{ zsh_config.path }} && cat {{ zsh_config.path }}
  register: newzsh
  become: true
  changed_when: oldzsh.stdout != newzsh.stdout
