- name: "{{ task_prefix }}Check if kitty is installed"
  stat:
    path: /opt/kitty.app
  register: _kitty

- name: "{{ task_prefix }}Install kitty"
  shell: 'curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin dest=/opt/ launch=n'
  become: true
  when: not _kitty.stat.exists

- name: "{{ task_prefix }}Create kitty link"
  file:
    src: /opt/kitty.app/bin/kitty
    dest: "{{ ansible_facts['env'].HOME }}/.local/bin/kitty"
    state: link

- name: "{{ task_prefix }}Create kitten link"
  file:
    src: /opt/kitty.app/bin/kitten
    dest: "{{ ansible_facts['env'].HOME }}/.local/bin/kitten"
    state: link

- name: "{{ task_prefix }}Check for local applications directory"
  stat:
    path: "{{ ansible_facts['env'].HOME }}/.local/share/applications"
  register: _appdir

- name: "{{ task_prefix }}Install desktop file"
  template:
    src: kitty.desktop.j2
    dest: "{{ _appdir.stat.path }}/kitty.desktop"
    mode: 0644
  when: _appdir.stat.exists and _appdir.stat.isdir
