- name: Import OS family tasks
  include_tasks: "{{ item }}"
  with_fileglob: "{{ os_family_lower }}.yml"
  vars:
    task_prefix: "{{ os_family_lower }} | "

- name: Import OS ID tasks
  include_tasks: "{{ item }}"
  with_fileglob: "{{ os_id }}.yml"
  vars:
    task_prefix: "{{ os_id }} | "
  when: os_family_lower != os_id

- name: "Add kitty ssh fix"
  blockinfile:
    path: "{{ shell_item.path }}"
    block: |
      # fixes unknown terminal issues with ssh
      [[ "$TERM" == "xterm-kitty" ]] && alias ssh="TERM=xterm-256color ssh"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} dotfile:kitty"
    marker_begin: '>>>'
    marker_end: '<<<'
  when: shell_item.exists
  loop: "{{ shell_configs }}"
  loop_control:
    loop_var: shell_item
