font_family             family="JetBrainsMono Nerd Font"
bold_font               auto
italic_font             auto
bold_italic_font        auto
font_size               10.5
modify_font             cell_height 110%
cursor_shape            block
shell_integration       no-cursor
enabled_layouts         splits

map ctrl+shift+-        launch --location=hsplit
map ctrl+shift+\        launch --location=vsplit
map ctrl+shift+,        set_tab_title
map ctrl+shift+=
map ctrl+=              change_font_size all +2.0
map ctrl+-              change_font_size all -2.0
map ctrl+0              change_font_size all 0

tab_bar_min_tabs        2
tab_bar_edge            bottom
tab_bar_style           powerline
tab_powerline_style     slanted
tab_title_template      {title}

# windows style right-click behavior
mouse_map right press ungrabbed kitten right_click_copy_paste.py

# custom techbase theme, using catppuccin template

foreground              #ccd5e5
background              #191d23
selection_foreground    #191d23
selection_background    #eeab41

cursor                  #5dcd9a
cursor_text_color       #191d23

url_style               straight
url_color               #ccd5e5

active_border_color     #eeab41
inactive_border_color   #6a7096
bell_border_color       #e5c07b

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #191d23
active_tab_background   #6a7096
inactive_tab_foreground #ccd5e5
inactive_tab_background #191d23
tab_bar_background      #191d23

mark1_foreground #191d23
mark1_background #748bdf
mark2_foreground #191d23
mark2_background #c678dd
mark3_foreground #191d23
mark3_background #62b5cc

# black
color0 #6a7096
color8 #6a7096

# red
color1 #f73e53
color9 #f73e53

# green
color2  #5dcd9a
color10 #5dcd9a

# yellow
color3  #e5c07b
color11 #e5c07b

# blue
color4  #748bdf
color12 #748bdf

# magenta
color5  #b17af5
color13 #b17af5

# cyan
color6  #6dbee3
color14 #6dbee3

# white
color7  #d6ddea
color15 #d6ddea
