- name: "Add key bindings to shell configs"
  blockinfile:
    path: "{{ shell_item.path }}"
    block: |
      if command -v fzf > /dev/null 2>&1; then
          source <(fzf --{{ shell_item.name }})
      fi
    append_newline: true
    prepend_newline: true
    marker: "# {mark} dotfile:fzf"
    marker_begin: '>>>'
    marker_end: '<<<'
  when: shell_item.exists
  loop: "{{ shell_configs }}"
  loop_control:
    loop_var: shell_item
