- name: "{{ os_family_lower}} | Check for current installation"
  stat:
    path: /opt/go
  register: _go

- name: Install golang
  block:
    - name: "{{ os_family_lower}} | Query latest version"
      uri:
        url: https://go.dev/dl/?mode=json
      register: go_dev_info
      changed_when: false

    - name: "{{ os_family_lower}} | Register latest version"
      set_fact:
        go_latest: "{{ go_dev_info.json[0].version }}"
      changed_when: false

    - name: "{{ os_family_lower }} | Register download target"
      set_fact:
        go_tarball: "{{ go_latest }}.{{ ansible_system | lower }}-{{ ansible_machine | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}.tar.gz"

    - name: "{{ os_family_lower }} | Download and extract tarball"
      unarchive:
        remote_src: true
        src: "https://golang.org/dl/{{ go_tarball }}"
        dest: /opt
      become: true

    - name: "{{ os_family_lower }} | Set directory permissions"
      file:
        path: /opt/go
        state: directory
        mode: 0755
        owner: root
        group: root
      become: true

    - name: "{{ os_family_lower }} | Add go to system-wide PATH"
      lineinfile:
        path: "/etc/profile.d/go.sh"
        line: 'export PATH=$PATH:/opt/go/bin:$HOME/go/bin'
        create: true
        mode: 0644
        state: present
      become: true

  when: not _go.stat.exists

- name: Install go tools
  include_tasks: install_tool.yml
  loop:
    - pkg: 'github.com/segmentio/golines@latest'
      name: golines
    - pkg: 'golang.org/x/tools/gopls@latest'
      name: gopls
    - pkg: 'honnef.co/go/tools/cmd/staticcheck@latest'
      name: staticcheck
    - pkg: 'mvdan.cc/gofumpt@latest'
      name: gofumpt
  loop_control:
    loop_var: gotool_item
