- name: "{{ gotool_item.name }} | Check if tool is installed"
  stat:
    path: "{{ ansible_facts['env'].HOME }}/go/bin/{{ gotool_item.name }}"
  register: gotool
  changed_when: false

- name: "{{ gotool_item.name }} | Install go tool"
  shell: "{{ gobin }} install '{{ gotool_item.pkg }}'"
  when: not gotool.stat.exists
