- name: "{{ task_prefix }}Install golang"
  community.general.homebrew:
    name: go
    state: latest

- name: "{{ task_prefix }}Set go bin path fact"
  set_fact:
    gobin: "go"

- name: "{{ task_prefix }}Install go tools"
  include_tasks: install_tool.yml
  loop: "{{ go_tools_macos }}"
  loop_control:
    loop_var: gotool_item
