- name: "Ensure config directory exists"
  file:
    path: "{{ ansible_facts['env'].HOME }}/.config/ghostty"
    state: directory

- name: "Install config"
  copy:
    src: config
    dest: "{{ ansible_facts['env'].HOME }}/.config/ghostty/config"
    mode: 0644

- ansible.builtin.import_tasks: "{{ playbook_dir }}/shared/include_os.yml"
