- name: "Ensure config directory exists"
  file:
    path: "{{ ansible_env.HOME }}/.config/ghostty"
    state: directory

- name: "Install config"
  copy:
    src: config
    dest: "{{ ansible_env.HOME }}/.config/ghostty/config"
    mode: 0644

- name: Import OS family tasks
  include_tasks: "{{ item }}"
  with_fileglob: "{{ os_family_lower }}.yml"
  vars:
    task_prefix: "{{ os_family_lower }} | "

- name: Import OS ID tasks
  include_tasks: "{{ item }}"
  with_fileglob: "{{ os_id }}.yml"
  vars:
    task_prefix: "{{ os_id }} | "
  when: os_family_lower != os_id
