- name: Import OS family tasks
  include_tasks: "{{ item }}"
  with_fileglob: "{{ os_family_lower }}.yml"
  vars:
    task_prefix: "{{ os_family_lower }} | "
  when: de_x11

- name: Import OS ID tasks
  include_tasks: "{{ item }}"
  with_fileglob: "{{ os_id }}.yml"
  vars:
    task_prefix: "{{ os_id }} | "
  when: de_x11 and os_family_lower != os_id
