- name: Import OS family tasks
  include_tasks: "{{ item }}"
  with_fileglob: "{{ os_family_lower }}.yml"
  vars:
    task_prefix: "{{ os_family_lower }} | "

- name: Import OS ID tasks
  include_tasks: "{{ item }}"
  with_fileglob: "{{ os_id }}.yml"
  vars:
    task_prefix: "{{ os_id }} | "
  when: os_family_lower != os_id

- name: Install tmux config
  copy:
    src: ".tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: 0644
