- name: "{{ task_prefix }}Ensure config directory exists"
  file:
    path: "{{ ansible_facts['env'].HOME }}/.config/lsd"
    state: directory

- name: "{{ task_prefix }}Install config"
  copy:
    src: "config.yaml"
    dest: "{{ ansible_facts['env'].HOME }}/.config/lsd"
    mode: 0644

- name: "{{ task_prefix }}Configure zsh"
  blockinfile:
    path: "{{ zsh_config.path }}"
    block: |
      alias ls='lsd'
      alias lt='lsd --tree'
    append_newline: true
    prepend_newline: true
    marker: "# {mark} dotfile:lsd"
    marker_begin: '>>>'
    marker_end: '<<<'
