- name: Install gpg
  become: true
  apt:
    state: latest
    pkg:
      - gpg
  when: os_family_lower == 'debian'

- name: Ensure gpg directory exists
  file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    state: directory
    mode: 0700

- name: Check for gpg-agent config
  stat:
    path: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
  register: gpgconf
  changed_when: false

- name: Install gpg config
  copy:
    src: "gpg-agent.conf"
    dest: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
    mode: 0644
  when: not gpgconf.stat.exists
