- name: "{{task_prefix}}Read grub config"
  shell: "cat /etc/default/grub"
  register: oldgrub
  changed_when: false

- name: "{{task_prefix}}Update grub timeout"
  shell: "sed -i 's/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=0/g' /etc/default/grub && cat /etc/default/grub"
  register: newgrub
  become: true
  changed_when: oldgrub.stdout != newgrub.stdout

- name: "{{task_prefix}}Update grub"
  shell: "update-grub"
  become: true
  when: oldgrub.stdout != newgrub.stdout
