set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g set-clipboard on
set -g history-limit 50000
set -g repeat-time 1000

# prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# better mouse behavior
set -g mouse on
bind m set -gF mouse "#{?mouse,off,on}" \; display "mouse: #{?mouse,on,off}"
unbind -T copy-mode-vi MouseDragEnd1Pane
unbind -T copy-mode-vi MouseDown3Pane
unbind -n MouseDown3Pane
bind -n MouseDown3Pane paste-buffer
bind -T copy-mode-vi MouseDown1Pane send-keys -X clear-selection
bind -T copy-mode-vi MouseDown3Pane send-keys -X copy-selection-and-cancel
bind -T copy-mode WheelUpPane send -N3 -X scroll-up
bind -T copy-mode WheelDownPane send -N3 -X scroll-down

# use 1-based index
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# use vim keys
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# fix esc delay in vim
set -g escape-time 10

# copy mode
unbind -T copy-mode-vi v
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi C-Home send-keys -X history-top
bind -T copy-mode-vi C-End send-keys -X history-bottom
bind -T copy-mode-vi C-Up send-keys -X halfpage-up
bind -T copy-mode-vi C-Down send-keys -X halfpage-down

# window management
bind c new-window -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind & kill-window
bind x kill-pane

# no prefix keys
bind -n M-S-Up select-pane -U
bind -n M-S-Down select-pane -D
bind -n M-S-Left select-pane -L
bind -n M-S-Right select-pane -R
bind -n M-X kill-pane
bind -n M-| split-window -h -c "#{pane_current_path}"
bind -n M-_ split-window -v -c "#{pane_current_path}"

# save pane to file
bind C-p command-prompt -p 'save pane to file:' \
    -I "#{pane_current_path}/#{session_name}_#{window_name}_%Y%m%d%H%M%S.txt" \
    'capture-pane -S - ; save-buffer %1 ; delete-buffer'

# styling
%if "#{==:#{TMUX_NONF},1}"
    HALF_ROUND_OPEN="#[reverse] #[default]"
    HALF_ROUND_CLOSE="#[reverse] #[default]"
%else
    HALF_ROUND_OPEN="#(printf '\uE0B6')"
    HALF_ROUND_CLOSE="#(printf '\uE0B4')"
%endif

setw -g automatic-rename off
set -g status-position top
set -g status-left-length 100
set -g status-right-length 100

set -g status-style fg=black,bg=default
set -g message-style fg=default,bg=default
set -g status-justify right
set -g status-left "#{?target,#([ -d /proc/sys/net/ipv4/conf/tun0 ] && ip -4 -br a sh dev tun0 | awk '{print $3#}' | cut -f1 -d/),}"
set -g status-right " ${HALF_ROUND_OPEN}#[fg=black,bold,reverse]#S#{?target,:#{target},}#[default]${HALF_ROUND_CLOSE}"
set -g window-status-format " #I:#W "
set -g window-status-current-format "#{?client_prefix,#[fg=yellow],#[fg=green]}${HALF_ROUND_OPEN}#{?client_prefix,#[fg=yellow],#[fg=green]}#[reverse,bold]#I:#W#[noreverse,nobold]${HALF_ROUND_CLOSE}"
set -g window-status-separator ""
set -g pane-border-style fg=black
set -g pane-active-border-style fg=white
set -g mode-style fg=yellow,reverse

# reload config
bind r source-file ~/.tmux.conf \; display "config reloaded"
