- name: "{{ task_prefix }}Check for current installation"
  stat:
    path: /opt/nvim
  register: _nvim

- name: "{{ task_prefix }}Install neovim"
  block:
    - name: "{{ task_prefix }}Register triple"
      set_fact:
        nvim_triple: "nvim-{{ ansible_system | lower }}-{{ ansible_machine }}"

    - name: "{{ task_prefix }}Download and extract tarball"
      unarchive:
        remote_src: true
        src: "https://github.com/neovim/neovim/releases/latest/download/{{ nvim_triple }}.tar.gz"
        dest: /opt/
        creates: "/opt/{{ nvim_triple }}"
        owner: root
        group: root
      retries: 2
      delay: 2
      become: true

    - name: "{{ task_prefix }}Rename directory"
      command: "mv /opt/{{ nvim_triple }} /opt/nvim"
      become: true

    - name: "{{ task_prefix }}Create symbolic link"
      file:
        src: /opt/nvim/bin/nvim
        dest: "/usr/local/bin/nvim"
        state: link
      become: true

  when: not _nvim.stat.exists
