- name: "{{ task_prefix }}Query latest version"
  uri:
    url: https://api.github.com/repos/neovim/neovim/releases/latest
  register: nvim_info
  changed_when: false

- name: "{{ task_prefix }}Register latest version"
  set_fact:
    nvim_latest: "nvim-{{ nvim_info.json.tag_name }}"
  changed_when: false

- name: "{{ task_prefix }}Check current installation"
  stat:
    path: "/opt/{{ nvim_latest }}"
  register: _nvim
  changed_when: false

- name: "{{ task_prefix }}Install neovim"
  block:
    - name: "{{ task_prefix }}Register triple"
      set_fact:
        nvim_triple: "nvim-{{ ansible_system | lower }}-{{ ansible_machine }}"

    - name: "{{ task_prefix }}Download and extract tarball"
      unarchive:
        remote_src: true
        src: "https://github.com/neovim/neovim/releases/latest/download/{{ nvim_triple }}.tar.gz"
        dest: /opt/
        creates: "/opt/{{ nvim_triple }}"
        owner: root
        group: root
      retries: 2
      delay: 2
      become: true

    - name: "{{ task_prefix }}Rename directory"
      command: "mv /opt/{{ nvim_triple }} /opt/{{ nvim_latest }}"
      become: true

    - name: "{{ task_prefix }}Link installed version"
      file:
        src: "/opt/{{ nvim_latest }}"
        dest: "/opt/nvim"
        state: link
      become: true

    - name: "{{ task_prefix }}Link binary"
      file:
        src: /opt/nvim/bin/nvim
        dest: "/usr/local/bin/nvim"
        state: link
      become: true

  when: not _nvim.stat.exists
