- name: "{{ task_prefix }}Install extra fonts"
  become: true
  apt:
    state: latest
    pkg: "{{ fonts_packages_debian }}"

- name: "{{ task_prefix }}Install nerd fonts"
  include_tasks: install_nerdfont.yml
  loop: "{{ fonts_nerdfonts_debian }}"
  loop_control:
    loop_var: font_item
