- name: "{{ task_prefix }}Install extra fonts"
  become: true
  apt:
    state: latest
    pkg:
      - fonts-inter
      - fonts-roboto
      - fonts-jetbrains-mono

- name: "{{ task_prefix }}Install nerd fonts"
  include_tasks: install_nerdfont.yml
  loop:
    - name: JetBrainsMono Nerd Font
      archive: JetBrainsMono.zip
    - name: Iosevka Nerd Font
      archive: Iosevka.zip
  loop_control:
    loop_var: font_item
